# Generated by Django 5.1.7 on 2025-03-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('fix_cost', models.FloatField()),
                ('variable_cost', models.FloatField()),
                ('capital', models.FloatField()),
            ],
        ),
    ]
