# Generated by Django 5.1.7 on 2025-03-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField()),
                ('expenses', models.FloatField()),
                ('salary_rd', models.IntegerField()),
                ('salary_maketing', models.IntegerField()),
                ('score_product', models.FloatField()),
                ('score_add', models.FloatField()),
                ('rival_info', models.TextField()),
            ],
        ),
    ]
